services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: libertadores-api
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - libertadores-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: libertadores-app
    volumes:
      - ./app:/app
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - api
    networks:
      - libertadores-network

networks:
  libertadores-network:
    driver: bridge